version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/sportspress-league-manager"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
