sonar.projectKey=lusky3_SportsPress-Admin-Tools
sonar.organization=lusk
sonar.sources=.
sonar.exclusions=**/vendor/**,**/assets/**,**/tests/**
sonar.php.exclusions=**/vendor/**,**/tests/**
sonar.issue.ignore.multicriteria=php:S100,php:S101,php:S116,php:S4833
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.php.coverage.reportPaths=coverage/clover.xml
