sonar.projectKey=lusky3_SportsPress-Admin-Tools
sonar.organization=lusk
sonar.sources=.
sonar.exclusions=**/vendor/**,**/assets/**,**/tests/**
sonar.php.exclusions=**/vendor/**,**/tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.php.coverage.reportPaths=coverage/clover.xml
