<?php
/**
 * XLSX Exporter Class
 * 
 * Exports schedules to Excel format with formatting and color-coding
 * 
 * @author Cody (lusky3)
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    wp_die();
}

/**
 * XLSX Exporter
 */
class SPSG_XLSX_Exporter implements SPSG_Exporter_Interface
{

    /**
     * Export schedule to XLSX format
     * 
     * @param array $schedule Array of game objects
     * @param mixed $config Configuration object or array
     * @return array|WP_Error Export result with file path and URL
     */
    public function export($schedule, $config = null)
    {
        // Check if PhpSpreadsheet is available
        if (!class_exists('PhpOffice\PhpSpreadsheet\Spreadsheet')) {
            error_log('[SPSG] PhpSpreadsheet not available, falling back to CSV export');
            $csv_exporter = new SPSG_CSV_Exporter();
            return $csv_exporter->export($schedule, $config);
        }

        try {
            $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
            $sheet = $spreadsheet->getActiveSheet();

            $this->set_document_properties($spreadsheet);
            $this->write_header_row($sheet);

            $row = $this->write_data_rows($sheet, $schedule);

            $this->apply_column_formatting($sheet, $row);

            return $this->save_spreadsheet($spreadsheet);

        } catch (Exception $e) {
            error_log('[SPSG] XLSX export error: ' . $e->getMessage());
            return new WP_Error('export_failed', __('Failed to export schedule to XLSX format', 'sportspress-schedule-generator'));
        }
    }

    /**
     * Set spreadsheet document properties
     */
    private function set_document_properties($spreadsheet)
    {
        $spreadsheet->getProperties()
            ->setCreator('SportsPress Schedule Generator')
            ->setTitle('League Schedule')
            ->setSubject('Generated League Schedule')
            ->setDescription('Schedule generated by SportsPress Schedule Generator plugin');
    }

    /**
     * Write and style the header row
     */
    private function write_header_row($sheet)
    {
        $headers = array(
            'Date', 'Start Time', 'End Time', 'Duration',
            'Home Team', 'Away Team', 'Venue', 'Division',
            'Home/Away', 'Inter-Division', 'Type', 'Week'
        );

        $col = 'A';
        foreach ($headers as $header) {
            $cell = $col . '1';
            $sheet->setCellValue($cell, $header);
            $style = $sheet->getStyle($cell);
            $style->getFont()->setBold(true);
            $style->getFont()->setSize(12);
            $style->getFill()
                ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
                ->getStartColor()->setARGB('FF4472C4');
            $style->getFont()->getColor()->setARGB('FFFFFFFF');
            $style->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
            $style->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
            $col++;
        }

        $sheet->getRowDimension('1')->setRowHeight(25);
    }

    /**
     * Write all game data rows and return the next row number
     */
    private function write_data_rows($sheet, $schedule)
    {
        $row = 2;
        $division_colors = $this->get_division_colors();
        $color_index = 0;
        $division_color_map = array();

        foreach ($schedule as $game) {
            $division_name = is_object($game->division) ? $game->division->name : $game->division;

            if (!isset($division_color_map[$division_name])) {
                $division_color_map[$division_name] = $division_colors[$color_index % count($division_colors)];
                $color_index++;
            }

            $this->write_game_row($sheet, $row, $game, $division_name, $division_color_map[$division_name]);
            $row++;
        }

        return $row;
    }

    /**
     * Write a single game row with data and styling
     */
    private function write_game_row($sheet, $row, $game, $division_name, $color)
    {
        $is_inter_division = $this->is_inter_division_game($game);
        $home_away = $this->get_home_away_designation($game);

        // Set cell values
        $sheet->setCellValue('A' . $row, $game->date);
        $sheet->setCellValue('B' . $row, $game->time_slot);
        $sheet->setCellValue('C' . $row, $game->end_time ?? '');
        $sheet->setCellValue('D' . $row, ($game->match_length ?? 60) . ' min');
        $sheet->setCellValue('E' . $row, is_object($game->home_team) ? $game->home_team->name : $game->home_team);
        $sheet->setCellValue('F' . $row, is_object($game->away_team) ? $game->away_team->name : $game->away_team);
        $sheet->setCellValue('G' . $row, is_object($game->venue) ? $game->venue->name : $game->venue);
        $sheet->setCellValue('H' . $row, $division_name);
        $sheet->setCellValue('I' . $row, $home_away);
        $sheet->setCellValue('J' . $row, $is_inter_division ? 'Yes' : 'No');
        $sheet->setCellValue('K' . $row, ($game->is_makeup ?? false) ? 'Makeup' : 'Regular');
        $sheet->setCellValue('L' . $row, $game->week_number ?? '');

        // Apply division color
        $sheet->getStyle('A' . $row . ':L' . $row)->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setARGB($color);

        // Center align date/time and status columns
        $center_cols = array('A', 'B', 'C', 'D', 'J', 'K', 'L');
        foreach ($center_cols as $col) {
            $sheet->getStyle($col . $row)->getAlignment()
                ->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
        }

        // Highlight inter-division games
        if ($is_inter_division) {
            $sheet->getStyle('J' . $row)->getFont()->setBold(true);
            $sheet->getStyle('J' . $row)->getFont()->getColor()->setARGB('FF0066CC');
        }

        // Highlight makeup games
        if ($game->is_makeup ?? false) {
            $sheet->getStyle('K' . $row)->getFont()->setBold(true);
            $sheet->getStyle('K' . $row)->getFont()->getColor()->setARGB('FFFF0000');
        }
    }

    /**
     * Apply column widths, borders, and freeze pane
     */
    private function apply_column_formatting($sheet, $row)
    {
        foreach (range('A', 'L') as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }

        // Minimum column widths
        $widths = array('A' => 12, 'B' => 10, 'C' => 10, 'D' => 10, 'I' => 25, 'J' => 12, 'K' => 10, 'L' => 8);
        foreach ($widths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        // Add borders
        $sheet->getStyle('A1:L' . ($row - 1))->applyFromArray(array(
            'borders' => array(
                'allBorders' => array(
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => array('argb' => 'FF000000'),
                ),
            ),
        ));

        $sheet->freezePane('A2');
    }

    /**
     * Save spreadsheet to file and return result
     */
    private function save_spreadsheet($spreadsheet)
    {
        $filename = 'schedule-' . date('Y-m-d-His') . '.xlsx';
        $upload_dir = wp_upload_dir();
        $file_path = $upload_dir['basedir'] . '/spsg-exports/' . $filename;

        if (!file_exists(dirname($file_path))) {
            wp_mkdir_p(dirname($file_path));
        }

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->save($file_path);

        return array(
            'path' => $file_path,
            'url' => $upload_dir['baseurl'] . '/spsg-exports/' . $filename,
            'filename' => $filename,
            'format' => 'xlsx'
        );
    }

    /**
     * Get division colors for formatting
     * 
     * @return array Array of color codes
     */
    private function get_division_colors()
    {
        return array(
            'FFE2EFDA', // Light green
            'FFFCE4D6', // Light orange
            'FFD9E1F2', // Light blue
            'FFFFF2CC', // Light yellow
            'FFF4B084', // Light coral
            'FFC5E0B4', // Sage green
            'FFB4C7E7', // Sky blue
            'FFFFD966', // Gold
            'FFE7E6E6', // Light gray
            'FFBDD7EE', // Powder blue
        );
    }

    /**
     * Get supported format
     * 
     * @return string Format identifier
     */
    public function get_format()
    {
        return 'XLSX';
    }


    /**
     * Get format name
     * 
     * @return string Human-readable format name
     */
    public function get_format_name()
    {
        return __('Excel (XLSX)', 'sportspress-schedule-generator');
    }

    /**
     * Get file extension
     * 
     * @return string File extension
     */
    public function get_extension()
    {
        return 'xlsx';
    }

    /**
     * Get MIME type
     * 
     * @return string MIME type
     */
    public function get_mime_type()
    {
        return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    }

    /**
     * Check if exporter supports formatting
     * 
     * @return bool True if formatting is supported
     */
    public function supports_formatting()
    {
        return true;
    }

    /**
     * Check if a game is inter-division
     * 
     * @param object $game Game object
     * @return bool True if inter-division
     */
    private function is_inter_division_game($game)
    {
        // Check if both teams have division IDs
        if (!isset($game->home_team->division_id) || !isset($game->away_team->division_id)) {
            // Fallback: check if game has is_inter_division property
            if (isset($game->is_inter_division)) {
                return $game->is_inter_division;
            }
            return false;
        }

        return $game->home_team->division_id !== $game->away_team->division_id;
    }

    /**
     * Get home/away designation for display
     * 
     * @param object $game Game object
     * @return string Home/Away designation
     */
    private function get_home_away_designation($game)
    {
        $home_name = is_object($game->home_team) ? $game->home_team->name : $game->home_team;
        $away_name = is_object($game->away_team) ? $game->away_team->name : $game->away_team;

        return sprintf('%s (H) vs %s (A)', $home_name, $away_name);
    }
}
