name: Code Quality (SonarCloud)

on:
  push:
    branches: [main]
    paths:
      - '**/*.php'
      - '**/*.js'
      - 'sonar-project.properties'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.php'
      - '**/*.js'
      - 'sonar-project.properties'

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
