name: Package & Release Plugins

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Create Zips
        run: |
          mkdir -p dist
          for dir in sportspress-*; do
            if [ -d "$dir" ]; then
              echo "Packaging $dir..."
              zip -r "dist/${dir}.zip" "$dir" -x "*/tests/*" "*/.git*" "*/composer.*" "*/node_modules/*" "*/assets/README*" "*/docs/*" "*/assets/wrangler.toml"
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          files: dist/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
