name: WordPress Plugin Check

on:
  push:
    branches: [main]
    paths:
      - '**/*.php'
  pull_request:
    branches: [main]
    paths:
      - '**/*.php'

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - sportspress-admin-tools
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1.1.5
        with:
          build-dir: ${{ matrix.plugin }}
          ignore-warnings: 'true'
          exclude-directories: tests,docs
          categories: general
          exclude-checks: i18n_usage
